CREATE TABLE nuevos (
	dept_no TINYINT(2) NOT NULL PRIMARY KEY,
	dnombre VARCHAR(15),
	loc	VARCHAR(15)
) ENGINE = InnoDB;

INSERT INTO nuevos VALUES (51, 'PERSONAL', 'MADRID');
INSERT INTO nuevos VALUES (52, 'NOMINAS', 'TOLEDO');
INSERT INTO nuevos VALUES (53, 'OCIO', 'BARCELONA');