package ud3_xampp;
// Generated 13-nov-2024 9:26:30 by Hibernate Tools 4.3.1



/**
 * Monumentos generated by hbm2java
 */
public class Monumentos  implements java.io.Serializable {


     private byte codigo;
     private String nombre;
     private String localidad;

    public Monumentos() {
    }

	
    public Monumentos(byte codigo) {
        this.codigo = codigo;
    }
    public Monumentos(byte codigo, String nombre, String localidad) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.localidad = localidad;
    }
   
    public byte getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(byte codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


