CREATE TABLE ALUMNOS2 OF T_ALUMNO;

INSERT INTO ALUMNOS2 VALUES(PERSONA(3,'ANA',DIRECCION('C/SEVILLA','GUADALAJARA',19006),SYSDATE),5,8,6);
INSERT INTO ALUMNOS2 VALUES(PERSONA(4,'MARÍA',DIRECCION('C/SEV','GUADALAJARA',19006),'01/01/2001'),6,7,8);
INSERT INTO ALUMNOS2 (AL) VALUES(PERSONA(5,'LUIS',DIRECCION('C/EL RAYO','BARCELONA',29007),'02/02/2002'));
INSERT INTO ALUMNOS2 (AL,nota1) VALUES(PERSONA(6,'JUAN',DIRECCION('C/EL RAYO 33','BARCELONA',29007),'03/03/2003'),5);

--USAR UN ALIAS PARA REFERIRNOS A LOS REGISTROS:
select A.AL.NOMBRE from alumnos2 A;

-- ACCEDER A LA NOTA MEDIA USANDO EL MÉTODO:
-- COALESCE, SI ES NULL DEVOLVER 0, O LO QUE SE LE INDIQUE.
select A.AL.NOMBRE, ROUND(COALESCE(A.MEDIAnOTAS(),0),2) from alumnos2 A;

-- USANDO CLAUSULAR WHERE
select A.AL.NOMBRE, A.AL.DIREC.CALLE, ROUND(COALESCE(A.MEDIAnOTAS(),0),2) from alumnos2 A
WHERE UPPER(A.AL.DIREC.CIUDAD) = 'GUADALAJARA' AND A.MEDIAnOTAS()> 6.5;

