package hibernate_examen;
// Generated 25-nov-2024 9:15:33 by Hibernate Tools 4.3.1



/**
 * NuevosProductos generated by hbm2java
 */
public class NuevosProductos  implements java.io.Serializable {


     private int codProd;
     private String pnombre;
     private Float precio;

    public NuevosProductos() {
    }

	
    public NuevosProductos(int codProd) {
        this.codProd = codProd;
    }
    public NuevosProductos(int codProd, String pnombre, Float precio) {
       this.codProd = codProd;
       this.pnombre = pnombre;
       this.precio = precio;
    }
   
    public int getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(int codProd) {
        this.codProd = codProd;
    }
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


