package hibernate_examen;
// Generated 25-nov-2024 9:15:33 by Hibernate Tools 4.3.1



/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private int numPed;
     private Productos productos;
     private String ncliente;
     private Float importe;

    public Pedidos() {
    }

	
    public Pedidos(int numPed, Productos productos) {
        this.numPed = numPed;
        this.productos = productos;
    }
    public Pedidos(int numPed, Productos productos, String ncliente, Float importe) {
       this.numPed = numPed;
       this.productos = productos;
       this.ncliente = ncliente;
       this.importe = importe;
    }
   
    public int getNumPed() {
        return this.numPed;
    }
    
    public void setNumPed(int numPed) {
        this.numPed = numPed;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getNcliente() {
        return this.ncliente;
    }
    
    public void setNcliente(String ncliente) {
        this.ncliente = ncliente;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }




}


