package hibernate_examen;
// Generated 25-nov-2024 9:15:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codProd;
     private String pnombre;
     private Float precio;
     private Set pedidoses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int codProd) {
        this.codProd = codProd;
    }
    public Productos(int codProd, String pnombre, Float precio, Set pedidoses) {
       this.codProd = codProd;
       this.pnombre = pnombre;
       this.precio = precio;
       this.pedidoses = pedidoses;
    }
   
    public int getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(int codProd) {
        this.codProd = codProd;
    }
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


